config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :jobs
    resources :instruments
    
    root "jobs#index"
    

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
    has_many :jobs
    accepts_nested_attributes_for :jobs
end

app/models/job.rb
class Job < ApplicationRecord
    has_one :instrument
    accepts_nested_attributes_for :instrument
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
    before_action :find_instrument, only: [:show, :edit, :update, :destroy]
    
    
    def index
        @instruments = Instrument.all
    end
    
    def show
    end
    
    def new
        @instrument = Instrument.new
    end
    
    def create
        @instrument = Instrument.new(instrument_params)
        if @instrument.save
            flash[:success] = "Instrument was successfully created"
            redirect_to 'instruments#index'
        else
            render @instruments
        end
    end
    
    def update
        if @instrument.update(instrument_params)
            flash[:success] = "Instrument was successfully updated"
            redirect_to root_path
        else
            render 'edit'
        end
        
    end
    
    def destroy
        if @instrument.destroy
            flash[:success] = "Instrument was successfully deleted"
            redirect_to root_path
        else
            flash[:danger] = "Instrument could not be deleted"
            redirect_to edit_instrument_path
        end
    end
    
    private
    def instrument_params
        params.require(:instrument).permit(:name, :ident, :model, :maker, :inst_type)
    end
    
    def find_instrument
        @instrument = Instrument.find(params[:id])
    end
    
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :find_job, only: [:show, :edit, :update, :destroy]
    
    
    def index
        @jobs = Job.all
    end
    
    def show
    end
    
    def new
        @job = Job.new
    end
    
    def create
        @job = Job.new(job_params)
        if @job.save
            flash[:success] = "Job was successfully created"
            redirect_to root_path
        else
            render @jobs
        end
    end
    
    def update
        if @job.update(job_params)
            flash[:success] = "Job was successfully updated"
            redirect_to @job
        else
            render 'edit'
        end
        
    end
    
    def destroy
        if @job.destroy
            flash[:success] = "Job was successfully deleted"
            redirect_to root_path
        else
            flash[:danger] = "Job could not be deleted"
            redirect_to edit_job_path
        end
    end
    
    private
    def job_params
        params.require(:job).permit(:name, :repair_type, :user_name, :comment)
    end
    
    def find_job
        @job = Job.find(params[:id])
    end
    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instrument_helper.rb
module InstrumentHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/instruments/_form.html.erb
<%= simple_form_for(@instrument, html: { class: 'form-horizontal' }) do |f| %>
    <%= f.input :name, input_html: { class: 'form-control' } %>
    <%= f.input :inst_type, priority: ["Measuring"], collection: ["Measuring", "Non-Measuring"], input_html: { class: 'form-control' } %>
    <%= f.input :maker, input_html: { class: 'form-control'} %>
    <%= f.input :ident, input_html: { class: 'form-control'} %>
    <%= f.input :model, input_html: { class: 'form-control'} %>
    <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/instruments/edit.html.erb
<%= render 'form' %>

app/views/instruments/index.html.erb
<div class="well col-md-8 col-md-offset-2">
    
    <div class="col-md-12">
        <% @instruments.each do |instrument| %>
            <div>
               <%= link_to instrument.name, instrument %>
            </div>
        <%end%>
    </div>    
</div>

app/views/instruments/new.html.erb
<%= render 'form' %>

app/views/instruments/show.html.erb
<div>
    <p><%= @instrument.name %></p>
    <p><%= @instrument.ident %></p>
    <p><%= @instrument.inst_type %></p>
    <p><%= @instrument.model %></p>
    <p><%= @instrument.maker %></p>
    <div class="col-md-6"> <!-- btn group -->
        <div class="btn-group pull-right"> <!-- groups the button to the right for improved aesthetic -->
            <%= link_to "Back", instruments_path, class:"btn btn-primary" %>
            <%= link_to "Edit", edit_instrument_path, class:"btn btn-warning" %>
            <!--The delete button is specific a bit here it sends the DELETE html method to the pin path -->
            <%= link_to "Delete", instrument_path, method: :delete, data: { confirm: "Are you sure" }, class:"btn btn-danger" %>
        </div>
    </div>
</div>

<%= link_to "Cancel", root_path, class:"btn btn-warning" %>

app/views/jobs/_form.html.erb
<%= simple_form_for(@job, html: { class: 'form-horizontal' }) do |f| %>
    <%= f.input :inst_name, input_html: { class: 'form-control' } %>
    <%= f.input :repair_type, priority: ["Repairs"], collection: ["Repairs", "Maintenance", "Notes"], input_html: { class: 'form-control' } %>
    <%= f.input :user_name, input_html: { class: 'form-control'} %>
    <%= f.input :comment, input_html: { class: 'form-control'} %>
    <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/jobs/index.html.erb
<div>
    <% @jobs.each do |job| %>
        <div class="well #{job.repair_type}">
            <div>
                <%= link_to job.inst_name, job %>
            </div>
        </div>
    <%end%>
        
</div>
<p>Find me in app/views/parts/index.html.erb</p>

app/views/jobs/show.html.erb
<div>
    <p><%= @job.inst_name %></p>
    <p><%= @job.user_name %></p>
    <p><%= @job.repair_type %></p>
    <p><%= @job.comment %></p>
    <div class="col-md-6"> <!-- btn group -->
        <div class="btn-group pull-right"> <!-- groups the button to the right for improved aesthetic -->
            <%= link_to "Back", root_path, class:"btn btn-primary" %>
            <%= link_to "Edit", edit_job_path, class:"btn btn-warning" %>
            <!--The delete button is specific a bit here it sends the DELETE html method to the pin path -->
            <%= link_to "Delete", job_path, method: :delete, data: { confirm: "Are you sure" }, class:"btn btn-danger" %>
        </div>
    </div>
</div>

<%= link_to "Cancel", root_path, class:"btn btn-warning" %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <!-- we refer to flash in the controllers -->
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}"if msg.is_a?(String) %>
      </div>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VariClassTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>